config:
  target: "https://api.yourdomain.com"
  phases:
    - name: warmup
      duration: 30
      arrivalRate: 20
    - name: ramp
      duration: 60
      arrivalRate: 50
      rampTo: 150
    - name: steady
      duration: 120
      arrivalRate: 150
  http:
    timeout: 200
    headers:
      X-Loadtest: "eco-bottle"
  plugins:
    expect: {}
  ensure:
    thresholds:
      - http.response_time.p95: 200
      - http.response_time.p99: 400
      - http.errors: 0
scenarios:
  - name: products list
    flow:
      - get:
          url: "/api/products?limit=12&page=1&sort=popularity"
          expect:
            - statusCode: 200
